repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
          'flake8-builtins==1.5.3',
          'flake8-comprehensions==3.8.0',
          'flake8-django==1.1.2',
          'flake8-eradicate==1.2.0',
          'flake8-print==4.0.0',
          'flake8-simplify==0.17.0',
          'pep8-naming==0.12.1',
          'flake8-annotations==2.7.0',
      ]
files: ^src/
exclude: ^src/management/commands/