name: Run Django tests

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: make up_build
      - name: Run tests
        run: make test
        env:
          DJANGO_PORT: 8000
          DJANGO_EXPOSE_PORT: 8000
          TARGET: development