name: Run Django tests

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Create env file
        run: touch .env
      - name: Up database
        run: make up_service_build service=db
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_VERSION: 13.4
          DJANGO_PORT: 8000
          DJANGO_EXPOSE_PORT: 8000
          TARGET: development
          RABBITMQ_VERSION: 3.8
      - name: Sleep for 30 seconds
          uses: jakejarvis/wait-action@master
          with:
            time: '15s'
      - name: Up backend
        run: make up_service_build service=web
        env:
          DJANGO_PORT: 8000
          DJANGO_EXPOSE_PORT: 8000
          TARGET: development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_VERSION: 13.4
          RABBITMQ_VERSION: 3.8
      - name: Run tests
        run: make test
